### ISSUE TITLE
NuGet warnings in .NET Core 2.2 App

### ISSUE THREAD

**Issue by stephajn** [tdayi/Fixer#1]
When using the NuGet package, the compiler is giving a warning.

Package 'Fixer 1.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

The project compiles just fine, but it seems that the package itself doesn't contain an assembly compiled against .NET Core 2.2.

**Comment by tdayi** [comment]
Hi @stephajn ,

Thank you for your feedback, this problem has been fixed in the new package.

https://www.nuget.org/packages/Fixer/1.1.1
