### ISSUE TITLE
First runs of tasks should respect the TimePattern

### ISSUE THREAD

**Issue by stephajn** [tdayi/Fixer#2]
When all scheduled tasks are added, they are automatically instantiated with their nextRun property set to DateTime.UtcNow.
`            var currentTime = DateTime.UtcNow;

            foreach (var scheduledTask in scheduledTasks)
            {
                fixerSchedulerTaskModels.Add(new FixerSchedulerTaskModel
                {
                    crontabSchedule = CrontabSchedule.Parse(scheduledTask.TimePattern),
                    schedulerTask = scheduledTask,
                    nextRunTime = currentTime
                });
            }`

If would be better and make more sense for nextRunTime to be populated with the CrontabSchedule.GetNextOccurrence instead, or perhaps allow the ISchedulerTask interface to have a property that dictates if it should run immediately on startup.

**Comment by tdayi** [comment]
Hi @stephajn ,

Thank you for your feedback, this problem has been fixed in this new package

can you visit here: https://github.com/tdayi/Fixer#appsettingsjson-configuration

https://www.nuget.org/packages/Fixer/1.1.1
