### ISSUE TITLE
Increasing Timeout

### ISSUE THREAD

**Issue by unsingned** [tdayi/Fixer#3]
Hi ,

Hope you are doing good and thanks for this wonderful nuget.
Is it possible for you to add the Task time out value in FixerSettings , as per my understanding currently the time out is hardcoded in FixerSchedulerHostedService.cs to one second?

 protected override async Task ExecuteAsync(CancellationToken cancellationToken)
        {
            while (!cancellationToken.get_IsCancellationRequested())
            {
                await this.ExecuteOnceAsync(cancellationToken);
                await Task.Delay(**TimeSpan.FromSeconds(1)**, cancellationToken);
            }
        }
we have some long-running tasks and  at times it goes beyond one sec and end up with the following exception.

System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Fixer.Hosting.FixerHostedService.StopAsync(CancellationToken cancellationToken)

Thanks
Rajesh

**Comment by tdayi** [comment]
Hi,

First of all sorry for the late reply

The purpose of this Task.Delay is to wait a second for the loop.

The loop checks each scheduler task every one second

Could the error be related to the code block you ran?
